[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "bonibello-tradein"

[services.source]
repo = "https://github.com/MrCamelHub/Trade-in"