[build]
builder = "nixpacks"

[deploy]
startCommand = "cd Delivery_API && python app.py"
restartPolicyType = "always"

[env]
PORT = "5000"
PYTHONPATH = "/app/Delivery_API"

# Railway에서 Delivery_API 폴더를 메인 앱으로 실행