[build]
builder = "nixpacks"
buildCommand = "cd Ship_API && pip install -r requirements.txt"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
startCommand = "cd Ship_API && python app.py"

[env]
TZ = "Asia/Seoul"
PYTHONPATH = "./Ship_API"

# 웹 서비스 - Flask 앱
[[services]]
name = "ship-api-web"

[services.variables]
TZ = "Asia/Seoul"
PYTHONPATH = "./Ship_API"
PORT = "8000"

# 샵바이 스케줄 서비스
[[services]]
name = "ship-shopby-scheduler"

[services.schedule]
# 매일 평일 12:00 (Asia/Seoul) - 샵바이 주문 조회
cron = "0 3 * * 1-5"  # UTC 03:00 = KST 12:00
command = "cd Ship_API && python -m main schedule-shopby"

[services.variables]
TZ = "Asia/Seoul"
PYTHONPATH = "./Ship_API"

# 코너로지스 스케줄 서비스
[[services]]
name = "ship-cornerlogis-scheduler"

[services.schedule]
# 매일 평일 12:59 (Asia/Seoul) - 코너로지스 업로드
cron = "59 3 * * 1-5"  # UTC 03:59 = KST 12:59
command = "cd Ship_API && python -m main schedule-cornerlogis"

[services.variables]
TZ = "Asia/Seoul"
PYTHONPATH = "./Ship_API"
