[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "ship-api"

[services.schedule]
# 매일 평일 13:00 (Asia/Seoul) 실행
cron = "0 4 * * 1-5"  # UTC 04:00 = KST 13:00
command = "python -m Ship_API.main schedule"

[services.variables]
TZ = "Asia/Seoul"
PYTHONPATH = "."
